language: node_js
node_js:
  - "node"
sudo: required
dist: trusty
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation festival
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 - sudo apt-get install graphicsmagick festival
before_script:
  - npm run setup
  - nohup bash -c "npm run server &> selenium-server.log &"
  - sleep 10
after_success:
  - npm run coverage
  - npm run lint
deploy:
  provider: npm
  email: andrej@chocolatejar.eu
  api_key: $NPM_TOKEN
  on:
    tags: true
